workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: 3.27.0   # exact version that uses AGP 8.9.1
      java: 17
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk